name: Weekly sync

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Execute sync script
        run: /bin/bash ./.script/sync.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update protobuf files
